---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels: { app: demo-app }
spec:
  replicas: 2
  selector:
    matchLabels: { app: demo-app }
  template:
    metadata:
      labels: { app: demo-app }
    spec:
      serviceAccountName: demo-app
      containers:
        - name: app
          image: IMAGE_PLACEHOLDER
          ports: [{ containerPort: 8080 }]
          readinessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 5
          livenessProbe:
            httpGet: { path: /livez, port: 8080 }
            initialDelaySeconds: 10
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demo-app-read
rules:
  - apiGroups: [""]
    resources: ["pods","configmaps"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-app-rb
subjects:
  - kind: ServiceAccount
    name: demo-app
roleRef:
  kind: Role
  name: demo-app-read
  apiGroup: rbac.authorization.k8s.io

