---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector: { app: {{ include "demo.name" . }} }
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080

